import type { InferGetServerSidePropsType } from "next";
import Head from "next/head";
import { Menu } from "../components/Menu";
import Image from "next/image";
import mariusDuke from "../../public/img/marius_duke.svg";
import javaZoneLogo from "../../public/img/logos/javazone-logo.jpg";
import octocat from "../../public/img/logos/github-logo.png";
import { Region } from "../components/Region";
import regions from "../../data/regions";
import members from "../../data/boardmembers";
import BoardMembers from "../components/BoardMembers";
import Link from "next/link";

const Home = (props: InferGetServerSidePropsType<typeof getStaticProps>) => {
  const yearsArrangingJavaZone = new Date().getFullYear() - 2002;
  return (
    <>
      <Head>
        <title>
          javaBin &mdash; Hjemmesiden til Javabrukerforeningen i Norge
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/icon" href="/img/favicon.ico" />
      </Head>
      <Menu />
      <header>
        <div className="container">
          <div className="intro-text">
            <Image priority src={mariusDuke} height={250} alt="Marius Duke" />
            <div className="intro-lead-in">Bli en del av noe stort</div>
            <div className="intro-heading">javaBin</div>
            <Link href="/#about" className="page-scroll btn btn-xl">
              Les om oss
            </Link>
          </div>
        </div>
      </header>

      <section id="about">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center">
              <h1 className="section-heading">Om javaBin</h1>
            </div>
          </div>
          <br />
          <div className="row">
            <div
              className="col-xs-12 col-sm-12 col-md-8 col-md-offset-2 center-justified">
              <p>
                javaBin er en av Norges største community-grupper, drevet av
                frivillige ildsjeler fra hele landet. Vi har avdelinger over
                hele landet – Stavanger, Bergen, Trondheim, Vestfold, Sogn,
                Tromsø, Sørlandet og Oslo. Hver eneste måned skjer det kule ting
                i javaBin-regi – både meetups, studentarrangementer,
                arrangementer for barn, og mye annet spennende!
              </p>
              <p>
                Hvert år i september er det duket for javaBins store happening
                –{" "}
                <Link href="http://javazone.no">JavaZone</Link>. Det stemmer! En
                av verdens største Java-konferanser er drevet av en frivillig
                organisasjon! Ca. 3.100 deltakere, 200 foredragsholdere, 50
                partnerbedrifter og generelt sett god stemning!
              </p>
              <p>
                Bli med på et javaBin-arrangement da vel! Og er du ekstra
                interessert, kan du snakke med oss og bli en av arrangørene. Vi
                er over 50 mennesker som bidrar med å skape kule arrangementer
                for våre nesten 3.000 medlemmer!
              </p>
            </div>
          </div>
        </div>
      </section>

      <section id="contribute">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center">
              <h1 className="section-heading">Vil du være med?</h1>
            </div>
          </div>
          <br />
          <div className="row">
            <div className="col-md-12">
              <ul className="timeline">
                <li className="timeline-default">
                  <div className="timeline-image">
                    <Image
                      className="img-circle img-responsive"
                      height={170}
                      src={mariusDuke}
                      alt="Marius Duke"
                    />
                  </div>
                  <div className="timeline-panel">
                    <div className="timeline-heading">
                      <h4>Bli aktiv i javaBin?</h4>
                    </div>
                    <div className="timeline-body">
                      <p>
                        Vil du være med aktivt i javaBin, og arrangere meetups
                        og JavaZone? I Oslo møtes vi hver tirsdag kl. 18:00
                        på{" "}
                        <Link href="https://goo.gl/maps/wpaA5nxxHM5ao3Rr9">
                          Teknologihuset
                        </Link>
                        på Rebel i Oslo Sentrum, og det er bare å dukke opp på
                        en av kveldene våre. I regionene møtes vi litt sjeldnere
                        – møt opp på et meetup-arrangement og snakk med oss.
                      </p>
                    </div>
                  </div>
                </li>

                <li className="timeline-inverted">
                  <div className="timeline-image">
                    <Image
                      className="img-circle img-responsive"
                      height={170}
                      src={javaZoneLogo}
                      alt="JavaZone logo"
                    />
                  </div>
                  <div className="timeline-panel">
                    <div className="timeline-heading">
                      <h4>Ideer til JavaZone?</h4>
                    </div>
                    <div className="timeline-body">
                      <p>
                        javaBin har arrangert{" "}
                        <Link href="http://javazone.no">JavaZone</Link> i
                        over{" "}
                        {yearsArrangingJavaZone} år nå. Ønsker du å bidra er du
                        hjertelig velkommen til dette! Ta kontakt med oss
                        på{" "}
                        <Link href="mailto:javazone@java.no">
                          javazone@java.no
                        </Link>{" "}
                        om du har ideer eller vil være med.
                      </p>
                    </div>
                  </div>
                </li>

                <li className="timeline-default">
                  <div className="timeline-image">
                    <Image
                      className="img-circle img-responsive"
                      height={170}
                      src={octocat}
                      alt="Github Octocat"
                    />
                  </div>
                  <div className="timeline-panel">
                    <div className="timeline-heading">
                      <h4>Liker du å kode? Bidra på GitHub!</h4>
                    </div>
                    <div className="timeline-body">
                      <p>
                        javaBin drives av utviklere og det fører med seg at vi
                        koder på en rekke prosjekter — alle er Open Source og
                        tilgjengelige på{" "}
                        <Link href="http://github.com/javabin">Github</Link>.
                      </p>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <section id="locations">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center">
              <h1 className="section-heading">Regioner</h1>
            </div>
          </div>
          {props.regions.map((region) => (
            <Region key={region.region} region={region} />
          ))}
        </div>
      </section>

      <section id="board">
        <BoardMembers boardMembers={props.boardMembers} />
      </section>

      {/*<Membership />*/}

      <section id="contact">
        <div className="container">
          <div className="row">
            <div className="col-md-12 text-center">
              <h1 className="section-heading">Kontakt</h1>
            </div>
          </div>
          <div className="row">
            <div className="col-md-12 center-justified">
              <form
                action="https://formspree.io/styret@java.no"
                method="POST"
                className="col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6"
              >
                <div className="form-group">
                  <label htmlFor="name">Navn</label>
                  <input
                    type="text"
                    className="form-control"
                    placeholder="Ditt navn"
                    name="name"
                    id="name"
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="email">Epost</label>
                  <input
                    type="email"
                    className="form-control"
                    placeholder="Din epost"
                    name="email"
                    id="email"
                  />
                </div>
                <div className="form-group">
                  <label htmlFor="message">Melding</label>
                  <textarea
                    name="message"
                    className="form-control"
                    placeholder="Din melding"
                    rows={5}
                    id="message"
                  ></textarea>
                </div>
                <div className="form-group">
                  <input
                    type="submit"
                    className="btn btn-primary"
                    value="Send"
                  />
                </div>
              </form>
            </div>
          </div>
          <div className="row">
            <div className="col-md-12 center-justified">
              <ul id="socialMedia">
                <li>
                  <Link
                    href="https://www.facebook.com/javabin"
                    className="icon fa fa-facebook"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>Facebook</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://github.com/javaBin"
                    className="icon fa fa-github"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>GitHub</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://instagram.com/javabin/"
                    className="icon fa fa-instagram"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>Instagram</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://twitter.com/javaBin"
                    className="icon fa fa-twitter"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>Twitter</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://vimeo.com/javabin"
                    className="icon fa fa-vimeo"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>Vimeo</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="https://linkedin.com/groups/107562"
                    className="icon fa fa-linkedin"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <span>LinkedIn</span>
                  </Link>
                </li>

                <li>
                  <Link
                    href="mailto:styret@java.no"
                    className="icon fa fa-envelope"
                    target=""
                  >
                    <span>Email</span>
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      <footer>
        <ul className="external">
          <li>
            <Link href="http://www.javazone.no" className="javazone">
              JavaZone
            </Link>
          </li>
          <li>
            <Link
              href="http://www.teknologihuset.no"
              className="teknologihuset"
            >
              Teknologihuset
            </Link>
          </li>
        </ul>
      </footer>
    </>
  );
};

// @ts-ignore
export async function getStaticProps () {
  const meetupRequest = await fetch(
    `https://api.meetup.com/2/events?group_id=7480032%2C8449272%2C7371452%2C4060032%2C10847532%2C1764379%2C30349557%2C32757331&status=upcoming&order=time&limited_events=False&desc=false&offset=0&format=json&page=20&fields=&sig_id=14499833`,
  )
  const events = await meetupRequest.json()

  const regionsnavnoverride = {
    javaBin: 'Oslo',
    'javaBin-Bergen': 'Bergen',
    'javaBin-Stavanger': 'Stavanger',
    'javaBin-Sorlandet': 'Sørlandet',
    'javaBin-Trondheim': 'Trondheim',
    'javaBin-Vestfold': 'Vestfold',
    'javaBin-Sogn': 'Sogn',
    'javaBin-Tromso': 'Tromsø',
  }

  const mapOfRegionsWithEvents = events.results.reduce((acc, current) => {
    const city = current?.venue?.city ?? 'Ukjent region'

    const index = regionsnavnoverride[current.group.urlname] || city;

    (acc[index] = acc[index] || []).push(current)
    return acc
  }, {})

  const regionsWithUpcomingMeetups = regions.map((region) => {
    region.events = mapOfRegionsWithEvents[region.region] ?? []
    return region
  })

  return {
    props: {
      regions: regionsWithUpcomingMeetups,
      boardMembers: members,
      revalidate: 3600,
    },
  }
}

export default Home
